### ISSUE TITLE
Shape an idea, test it with realworld code, remove unnecessary code

### ISSUE THREAD

**Issue by 18augst** [18augst/metapp#29]

**Comment by 18augst** [comment]
### TODO

- [ ] a.Equal(tA, app, "We should use one pointere everywhere in program.")
- [ ] Test default & custom behaviors
- [ ] Test with not existing configuration file.
- [ ] Test with existing and not supported configuration file.
- [ ] Handle destructors.
- [ ] Write generators for shortcuts for finding a value of a type in a list of a type(Slice|Array|Map?). Write test cases.

**Comment by 18augst** [comment]
Transform each default behavior into a `Go` package. Distribute `A` structure fields between packages namespaces.

https://github.com/18augst/berry/issues/9
https://github.com/18augst/berry/issues/10
https://github.com/18augst/berry/issues/11

**Comment by 18augst** [comment]
Create testing script. Update *Readme* and *Godoc*.
